#!/bin/bash
#This script must be called in the "Run" script
inSpeed = (1 2 3 4 5 6 7 8 9 10 11 12);
inZref = (10 10 10 10 10 10 10 10 10 10 10 10);
inZ0 = (0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1);

read a
read b
read c

#Ns numero da linha do arquivo U
Ns=5
stringToChange="value     uniform (a b c);"


#How to change values in the target dictionary:
sed -i '/Uref/c\Uref                 11.0;' 0.orig/include/ABLConditions

sed -i '/Zref/c\Zref                 20;' 0.orig/include/ABLConditions

sed -i '/z0/c\z0                   uniform 0.1;' 0.orig/include/ABLConditions
#---------------------------------------------------
